# Numpy

In [1]:
# first of all, import numpy

import numpy as np

In [5]:
# generating a list of random numbers

arr0 = np.random.rand(3,4)

In [6]:
# to form a list

arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([9,10,11,12,13,14,15,16])

In [7]:
# performing addition

result1 = arr1 + arr2

In [8]:
print(result1)

[10 12 14 16 18 20 22 24]


In [11]:
# performing subtraction

result2 = arr1 - arr2
print(result2)

[-8 -8 -8 -8 -8 -8 -8 -8]


In [12]:
# performing multiplication

result3 = arr1 * arr2
print(result3)

[  9  20  33  48  65  84 105 128]


In [13]:
# performing dividion

result4 = arr1 / arr2
print(result4)

[0.11111111 0.2        0.27272727 0.33333333 0.38461538 0.42857143
 0.46666667 0.5       ]


In [19]:
# Creating a numpy array indexing and slicing
print(arr2[0])
print(arr2[1])
print(arr2[2])
print(arr2[3])
print(arr2[4])
print(arr2[5])
print(arr2[-1])

9
10
11
12
13
14
16


In [23]:
print(arr[1:4])
print(arr[:6])
print(arr[2:])

[2 3 4]
[1 2 3 4 5 6]
[3 4 5 6 7 8]


In [24]:
print(arr0)

[[0.18113545 0.25585507 0.03287313 0.89238538]
 [0.36440798 0.97533977 0.85856408 0.9632565 ]
 [0.6490702  0.55569558 0.71679459 0.85252285]]


In [27]:
print(arr0.reshape(6,2))

[[0.18113545 0.25585507]
 [0.03287313 0.89238538]
 [0.36440798 0.97533977]
 [0.85856408 0.9632565 ]
 [0.6490702  0.55569558]
 [0.71679459 0.85252285]]


In [26]:
print(arr0)

[[0.18113545 0.25585507 0.03287313 0.89238538]
 [0.36440798 0.97533977 0.85856408 0.9632565 ]
 [0.6490702  0.55569558 0.71679459 0.85252285]]


In [28]:
# performing numpy with aggregate function
arr3 = arr0.reshape(6,2)

In [29]:
print(arr3)

[[0.18113545 0.25585507]
 [0.03287313 0.89238538]
 [0.36440798 0.97533977]
 [0.85856408 0.9632565 ]
 [0.6490702  0.55569558]
 [0.71679459 0.85252285]]


In [30]:
print(np.sum(arr3))

7.297900556648125


In [32]:
# performing mean
print(np.mean(arr3))

0.6081583797206771


In [33]:
np.sort(arr3)

array([[0.18113545, 0.25585507],
       [0.03287313, 0.89238538],
       [0.36440798, 0.97533977],
       [0.85856408, 0.9632565 ],
       [0.55569558, 0.6490702 ],
       [0.71679459, 0.85252285]])

In [36]:
# Broadcasting

arr4 = np.array([12,34,46,78])
arr5 = np.array([108])
result5 = arr4 + arr5

In [37]:
print(result5)

[120 142 154 186]


In [40]:
#advance indexing

arr6 = np.array([[2,6,3,8,5], [1,6,9,12,15]])

In [44]:
#accessing rows and columns
print(arr6[0,3])
print(arr6[1:])
print(arr6[[0,1], [2,3]])

8
[[ 1  6  9 12 15]]
[ 3 12]


In [47]:
print(arr6.shape)

(2, 5)


In [48]:
#Initializing different types of array
# Zero matix

arr7 = np.zeros(7)

In [49]:
print(arr7)

[0. 0. 0. 0. 0. 0. 0.]


In [50]:
arr8 = np.zeros([2,3,3,2])

In [51]:
print(arr8)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [62]:
arr9 = np.full((3,4),2)

In [63]:
print(arr9)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [71]:
# random decimal values

np.random.rand(5,9)

array([[0.30569783, 0.25251845, 0.2473378 , 0.76457328, 0.18286793,
        0.55001628, 0.51389067, 0.18443924, 0.78160963],
       [0.84346401, 0.72076546, 0.99840044, 0.60332128, 0.89303473,
        0.36205657, 0.16524555, 0.68336627, 0.57598969],
       [0.59221669, 0.71157898, 0.21432531, 0.16404735, 0.48350982,
        0.69629322, 0.59732032, 0.67264837, 0.81403808],
       [0.7782325 , 0.51290423, 0.79121068, 0.82606353, 0.98101472,
        0.95838874, 0.27133154, 0.60299858, 0.21127884],
       [0.8975702 , 0.84777694, 0.12166267, 0.83956493, 0.15406499,
        0.60091108, 0.66208094, 0.19332495, 0.47815769]])

In [70]:
# random integer values

np.random.randint(5, size = (3,4))

array([[3, 4, 4, 1],
       [4, 4, 1, 4],
       [0, 0, 4, 0]])

In [73]:
# Performing identity
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [75]:
# Joing two arrays
arr10 = np.concatenate((arr1, arr2))

In [76]:
print(arr10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [86]:
arr11 = np.random.randint(4, size = (4,4))
arr12 = np.random.randint(5, size = (4,4))

In [87]:
print(arr11)
print('')
print(arr12)

[[2 2 2 3]
 [2 0 0 0]
 [2 0 0 1]
 [2 1 1 0]]

[[0 1 4 3]
 [1 4 2 1]
 [2 3 4 3]
 [4 0 3 0]]


In [88]:
result7 = np.concatenate((arr11,arr12))

In [89]:
print(result7)

[[2 2 2 3]
 [2 0 0 0]
 [2 0 0 1]
 [2 1 1 0]
 [0 1 4 3]
 [1 4 2 1]
 [2 3 4 3]
 [4 0 3 0]]


In [103]:
# 2-D arrays along row(axis = 1)
arr13 = arr11
arr14 = arr12

In [106]:
print(arr13)
print('')
print(arr14)

[[2 2 2 3]
 [2 0 0 0]
 [2 0 0 1]
 [2 1 1 0]]

[[0 1 4 3]
 [1 4 2 1]
 [2 3 4 3]
 [4 0 3 0]]


In [99]:
# 2-D arrays along row(axis = 1)
arra1 = np.array([[1,2], [3,4]])
arra2 = np.array([[5,6], [7,8]])

result_1 = np.concatenate((arra1, arra2), axis = 1)
print(result_1)

[[1 2 5 6]
 [3 4 7 8]]


In [105]:
result_2 = np.stack((arr13,arr14), axis=1)
print(result_2)

[[[2 2 2 3]
  [0 1 4 3]]

 [[2 0 0 0]
  [1 4 2 1]]

 [[2 0 0 1]
  [2 3 4 3]]

 [[2 1 1 0]
  [4 0 3 0]]]


In [110]:
# Spliting numpy arrays

result_3 = np.array_split(arr10, 4)
print(result_3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12]), array([13, 14, 15, 16])]


In [113]:
#array search 
arra3 = np.array([1,2,3,4,5,4,4])
x = np.where(arra3 == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [114]:
# to find even value

arra4 = np.array([1,2,3,4,5,6,7,8,9])
y = np.where(arra4 % 2 == 0)
print(y)

(array([1, 3, 5, 7], dtype=int64),)


In [115]:
# to find even value

arra4 = np.array([1,2,3,4,5,6,7,8,9])
y = np.where(arra4 % 2 == 1)
print(y)

(array([0, 2, 4, 6, 8], dtype=int64),)


In [119]:
#data distribution
from numpy import random
c = random.choice([3,5,7,9], p = [0.1,0.3,0.6,0.0], size=100)
print(c)

[7 7 7 3 7 7 7 7 7 7 3 5 5 7 5 5 7 7 7 7 5 7 7 7 7 7 7 5 5 7 5 7 7 5 5 5 7
 7 7 7 7 5 7 5 3 7 7 3 7 3 5 5 7 7 7 7 7 7 5 5 5 7 7 3 7 7 7 7 3 7 7 5 7 7
 5 5 5 5 7 7 7 7 3 7 5 7 3 7 5 3 5 7 5 7 7 5 5 7 5 5]


In [122]:
#data distribution
from numpy import random
d = random.choice([3,5,7,9], p = [0.1,0.3,0.6,0.0], size=(3,5))
print(d)

[[7 7 3 5 7]
 [7 7 7 7 5]
 [7 7 3 5 7]]
